objects/Invoice_Statement__c.object
<CustomObject>
    <description>it is object for invoice statement object showing the status and description for that</description>
    <fields>
        <fullName>City__c</fullName>
        <description>here is the city of that  customer</description>
        <label>City</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Company_Name__c</fullName>
        <description>here is company name for invoice statement</description>
        <label>Company Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Email_Address__c</fullName>
        <description>here is email address of that customer</description>
        <label>Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Grand_Total__c</fullName>
        <description>here is grand total of all line items</description>
        <label>Grand Total</label>
        <summarizedField>Line_Item__c.Amount__c</summarizedField>
        <summaryForeignKey>Line_Item__c.Invoice_Statement_No__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Name_Of_Customer__c</fullName>
        <description>here is name of that customer</description>
        <label>Name Of Customer</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Phone_Number__c</fullName>
        <description>here is phone number of that customer</description>
        <label>Phone Number</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stree_Address__c</fullName>
        <description>here is address of that customer</description>
        <label>Stree Address</label>
        <type>TextArea</type>
    </fields>
    <label>Invoice Statement</label>
    <nameField>
        <displayFormat>INV-{000000}</displayFormat>
        <label>Invoice Statement No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Line_Item__c.object
<CustomObject>
    <description>it is used as junction object to store the records</description>
    <fields>
        <fullName>Amount__c</fullName>
        <description>here is total amount for that</description>
        <formula>Unit_Price__c  *  Unit_Sold__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Description_of_Item__c</fullName>
        <description>description of item purchased</description>
        <label>Description of Item</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Invoice_Statement_No__c</fullName>
        <description>here is invoice statement no to which it belongs</description>
        <label>Invoice Statement No</label>
        <referenceTo>Invoice_Statement__c</referenceTo>
        <relationshipLabel>Line Item</relationshipLabel>
        <relationshipName>Line_Item</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <displayFormat>ITEM-{0000}</displayFormat>
        <label>Line Item No</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Line Item</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

classes/InvoiceVfPageController.cls
/******************************************************************************
*  It is controller class for Invoice Statement
********************************************************************************/
public with sharing class InvoiceVfPageController {
    public List<Invoice_Statement__c> listInvoice;
    public List<Line_Item__c> lineItemList;
    public Id invoice_Id{get;set;}
    public Id invoiceIdToPass{get;set;}
    /*
     *  Method To show all records of invoice statement to a table page 
     */
    public List<Invoice_Statement__c> getlistInvoice() {
        listInvoice=[SELECT Id,
                            Name,
                            City__c,
                            Company_Name__c,
                            Email_Address__c,
                            Name_Of_Customer__c,
                            Phone_Number__c,
                            Stree_Address__c
                     FROM Invoice_Statement__c];
        return listInvoice;
    }
    
    /*
     *  Method To show pdf page 
     */
     public PageReference goToPdfPage() {
        invoice_Id= apexpages.currentpage().getparameters().get('invoiceId');
        System.debug('====id in page diveert==='+invoice_Id);
        PageReference pdfPage=Page.InvoicePdf; 
        pdfPage.setRedirect(True);
        pdfPage.getparameters().put('invoiceID',invoice_Id);
        return pdfPage;
    } // End of method   
    
    public List<Line_Item__c> getlineItemList()
    {
        invoiceIdToPass=apexPages.currentPage().getParameters().get('invoiceID');
        System.debug('====idd==='+invoiceIdToPass);
        lineItemList=[SELECT Id,
                             Name,
                             Amount__c,
                             Description_of_Item__c
                      FROM Line_Item__c 
                      WHERE Invoice_Statement_No__c= :invoiceIdToPass];
         listInvoice=[SELECT Id,
                            Name,
                            City__c,
                            Company_Name__c,
                            Email_Address__c,
                            Name_Of_Customer__c,
                            Phone_Number__c,
                            Stree_Address__c,
                            Grand_Total__c
                     FROM Invoice_Statement__c];
         System.debug('====List==='+lineItemList);
                      
        return lineItemList;
    }
} // End of controller class